# .github/workflows/monitor.yml
name: ManagerZone Forum Monitor

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite execução manual

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
    
    - name: Run monitor
      run: python monitor_single_run.py
    
    - name: Commit and push state
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add forum_state.json || true
        git diff --staged --quiet || git commit -m "Update forum state [skip ci]"
        git push || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
